### ISSUE TITLE
Unauthorized. No permission

### ISSUE THREAD

**Issue by Sally-Yang-Jing-Ou** [neo4j-examples/movies-python-neo4jrestclient#1]
Hello Neo4j,

I was trying to run this application. I've created my virtual environment, and created the movies data on neo4j web browser. But when I did `python movies.py`, the error is shown up as `neo4jrestclient.exceptions.StatusException: Code [401]: Unauthorized. No permission -- see authorization schemes.
Authorization Required`

Any idea why?

Thanks so much,
Sally

**Comment by jexp** [comment]
You either have to disable auth in Neo4j (conf/neo4j-server.properties)

Or provide your username `neo4j` and password `???` to the application.

http://neo4j-rest-client.readthedocs.org/en/latest/info.html#authentication

**Comment by Sally-Yang-Jing-Ou** [comment]
Hello @jexp, I've tried disabling auth in Neo4j:
`# Require (or disable the requirement of) auth to access Neo4j`
`# dbms.security.auth_enabled=true`
as well as tried providing usrname and password, here's what I did:
`>>> url ="http://localhost:7474/db/data/"`
 `>>> gdb=GraphDatabase(url, username="neo4j", password="neo4j")`
Unfortunately, I am still getting the same error.

Any ideas? :( 

Thanks,
Sally

**Comment by jexp** [comment]
If you disable auth in the config file (set it to false) you have to restart neo4j.
If you use auth, you have to set the initial password first by connecting to neo4j with the browser.

**Comment by Sally-Yang-Jing-Ou** [comment]
Thanks!!

**Comment by Saharsh007** [comment]
worked like charm , thanks @jexp
